backend:
  name: github
  repo: foresyndo/payraya
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "dashboard"
    label: "Dashboard"
    files:
      - file: "public/content/dashboard.json"
        label: "Dashboard Content"
        name: "dashboard"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Deskripsi", name: "description", widget: "text" }
